# Generated by Django 3.1.12 on 2021-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Rojo'), ('#0000FF', 'Azul'), ('#FFFF00', 'Amarillo'), ('#800080', 'Morado')], max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
